first commit of hibernate hw
Alekearl/Cinema-project pull request #1
Opened 2021-01-26 17:46 UTC by Alekearl

2021-01-26 19:43 UTC, engineer027 commented on src/main/java/com/dev/cinema/service/serviceimpl/MovieServiceImpl.java
> +
лишня строка

2021-01-26 19:43 UTC, engineer027 commented on src/main/java/com/dev/cinema/dao/daoimpl/MovieDaoImpl.java
> +        }
Якщо в тебе в блоці try вилетить помилка, ти не зможеш виконати .rollback(), тому що сесія уже закриється, спробув використати блок finally

2021-01-26 20:03 UTC, Alekearl commented on src/main/java/com/dev/cinema/service/serviceimpl/MovieServiceImpl.java
> +
прибрав.

2021-01-26 20:06 UTC, Alekearl commented on src/main/java/com/dev/cinema/dao/daoimpl/MovieDaoImpl.java
> +        }
Якраз пред твоїм зауваженням, перечитав ще раз checklist де вказано використати try with final з транзакціями і з ресурсами якщо операції тільки для зчитування.

2021-01-26 20:11 UTC, engineer027 approved these changes

2021-01-27 08:09 UTC, Sofasmile requested changes

2021-01-27 08:09 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/daoimpl/MovieDaoImpl.java
> +            movie.setId(itemId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 08:09 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/daoimpl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert movie entry", e);
```suggestion
            throw new DataProcessingException("Can't insert movie entry " + movie, e);
```

2021-01-27 09:30 UTC, Alekearl commented on src/main/java/com/dev/cinema/dao/daoimpl/MovieDaoImpl.java
> +            movie.setId(itemId);
One check  missed, sorry. Changed.

2021-01-27 10:14 UTC, RomanDubovskyi approved these changes

2021-01-27 11:33 UTC, merged